language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yuoo1580/practice-react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true yuoo1580/practice-react-docker npm run test # -e 代表由user自定義環境變數 設置CI=true create-react-app 會在測試結束後自動結束

deploy:
  provider: elasticbeanstalk # 指定aws elastic beanstalk
  region: "us-east-2" # server的地區 可以透過網址得到 http://practicereactdocker-env.eba-jgdqvumr.us-east-2.elasticbeanstalk.com/
  app: "practice-docker-react" # 建立的app名稱
  env: "PracticeDockerReact-env" # 自動建立的環境名稱
  bucket_name: "elasticbeanstalk-us-east-2-585582745139" # 儲存的名稱 可以透過s3查到
  bucket_path: "practice-docker-react"
  on:
    branch: master # 只當master branch變動時才重新部署
  access_key_id: $AWS_ACCESS_KEY # 使用環境變數
  secret_access_key: $AWS_SECRET_KEY
